<?php

namespace GestionBundle\Repository;

/**
 * ChangementBaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChangementBaseRepository extends \Doctrine\ORM\EntityRepository
{
	public function findDateChangement($pilote)
    {
        return $this
          ->createQueryBuilder('c')
          ->where("c.pilote = :pilote")
          ->setParameters(array(
                                'pilote'=> $pilote))->getQuery()->getResult();

    }
}
