<?php

namespace GestionBundle\Repository;

/**
 * FlotteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlotteRepository extends \Doctrine\ORM\EntityRepository
{

	
	public function findByFlotte($flotte)
    {
        return $this
          ->createQueryBuilder('f')
          ->where("f.typeFlotte = :flotte")
          ->setParameters(array(
                                'flotte'=> $flotte))->getQuery()->getResult();

    }
}
