<?php

namespace GestionBundle\Repository;

/**
 * IndisponibleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndisponibleRepository extends \Doctrine\ORM\EntityRepository
{

	public function findDateIndispo($pilote)
    {
        return $this
          ->createQueryBuilder('i')
          ->where("i.pilote = :pilote")
          ->setParameters(array(
                                'pilote'=> $pilote))->getQuery()->getResult();

    }
    /* Recherche si un evenement est en cours a Today */
    public function getEventIndisponible($today, $pilote) {
        
        $parameters = array();
        $parameters['today'] = $today;
        $parameters['idPilote'] = $pilote;
        
        $qb = $this->createQueryBuilder('n');
        $qb->join('n.pilote', 'p');
        $qb->select('n');
        $qb->andWhere(
            $qb->expr()->orX(
                $qb->expr()->andX(':idPilote = n.pilote'),
                $qb->expr()->andX(':today <= n.dateDebut', ':today >= n.dateFin')
                ));
        
        $qb->setParameters($parameters);
        return $qb->getQuery()->getResult();
    }
    
    /* Recherche si un evenement existe deja */

    public function getEventIndisponibleWithDate($debut, $fin, $pilote) {
        
        $parameters = array();
        $parameters['debut'] = $debut;
        $parameters['fin'] = $fin;
        $parameters['idPilote'] = $pilote;
        
        $qb = $this->createQueryBuilder('n');
        $qb->join('n.pilote', 'p');
        $qb->select('n');
        
        $qb->andWhere(':idPilote = n.pilote');
        $qb->andWhere(
            $qb->expr()->orX(
                $qb->expr()->andX('n.dateDebut <=  :debut', 'n.dateFin > :debut'),
                $qb->expr()->andX('n.dateDebut >= :debut', 'n.dateFin <= :fin'),
                $qb->expr()->andX('n.dateDebut <= :debut', 'n.dateFin <= :fin','n.dateFin > :debut'),
                $qb->expr()->andX('n.dateDebut >= :debut','n.dateFin >= :fin', 'n.dateDebut < :fin'
                    )
                ));
        
        $qb->setParameters($parameters);
        return $qb->getQuery()->getResult();
    }
}
