<?php

namespace GestionBundle\Repository;

/**
 * NominationDenominationCadreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NominationDenominationCadreRepository extends \Doctrine\ORM\EntityRepository
{
	public function findDateCadre($pilote)
    {
        return $this
          ->createQueryBuilder('c')
          ->where("c.pilote = :pilote")
          ->setParameters(array(
                                'pilote'=> $pilote))->getQuery()->getResult();

    }
    
    /* Recherche si un evenement est en cours a Today */
    public function getEventCadre($today, $pilote) {
        
        $parameters = array();
        $parameters['today'] = $today;
        $parameters['idPilote'] = $pilote;
        
        $qb = $this->createQueryBuilder('n');
        $qb->join('n.pilote', 'p');
        $qb->select('n');
        $qb->andWhere(':idPilote = n.pilote');
        $qb->andWhere(
            $qb->expr()->orX(
                $qb->expr()->andX(':today >= n.dateNomination', ':today <= n.dateDenomination')
                ));
        
        $qb->setParameters($parameters);
        return $qb->getQuery()->getResult();
    }
    
    public function getEventCadreWithDate($debut, $fin, $pilote) {
        
        $parameters = array();
        $parameters['debut'] = $debut;
        $parameters['fin'] = $fin;
        $parameters['idPilote'] = $pilote;
        
        $qb = $this->createQueryBuilder('n');
        $qb->join('n.pilote', 'p');
        $qb->select('n');
        
        $qb->andWhere(':idPilote = n.pilote');
        $qb->andWhere(
            $qb->expr()->orX(
                $qb->expr()->andX('n.dateNomination <=  :debut', 'n.dateDenomination > :debut'),
                $qb->expr()->andX('n.dateNomination >= :debut', 'n.dateDenomination <= :fin'),
                $qb->expr()->andX('n.dateNomination <= :debut', 'n.dateDenomination <= :fin','n.dateDenomination > :debut'),
                $qb->expr()->andX('n.dateNomination >= :debut','n.dateDenomination >= :fin', 'n.dateNomination < :fin'
                    )
                ));
        
        $qb->setParameters($parameters);
        return $qb->getQuery()->getResult();
    }
}
