<?php

namespace GestionBundle\Repository;

/**
 * pretInterSecteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pretInterSecteurRepository extends \Doctrine\ORM\EntityRepository
{
	public function findDatePret($pilote)
    {
        return $this
          ->createQueryBuilder('p')
          ->where("p.pilote = :pilote")
          ->setParameters(array(
                                'pilote'=> $pilote))->getQuery()->getResult();

    }
    
    /* Recherche si un evenement est en cours a Today */
    public function getEventPis($today, $pilote) {
        
        $parameters = array();
        $parameters['today'] = $today;
        $parameters['idPilote'] = $pilote;
        
        $qb = $this->createQueryBuilder('n');
        $qb->join('n.pilote', 'p');
        $qb->select('n');
        $qb->andWhere(
            $qb->expr()->orX(
                $qb->expr()->andX(':idPilote = n.pilote'),
                $qb->expr()->andX(':today <= n.dateDebutPret', ':today >= n.dateFinPret')
                ));
        
        $qb->setParameters($parameters);
        return $qb->getQuery()->getResult();
    }
}
