<?php

namespace GestionBundle\Repository;

/**
 * ProlongationFCSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProlongationFCSRepository extends \Doctrine\ORM\EntityRepository
{
}
