<?php

namespace GestionBundle\Repository;

/**
 * StagiaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StagiaireRepository extends \Doctrine\ORM\EntityRepository
{
    
    /* Recherche si un evenement existe deja */
    
    public function getEventStagiaireWithDate($debut, $fin, $pilote) {
        
        $parameters = array();
        $parameters['debut'] = $debut;
        $parameters['fin'] = $fin;
        $parameters['idPilote'] = $pilote;
        
        $qb = $this->createQueryBuilder('n');
        $qb->join('n.pilote', 'p');
        $qb->select('n');
        
        $qb->andWhere(':idPilote = n.pilote');
        $qb->andWhere(
            $qb->expr()->orX(
                $qb->expr()->andX('n.dateDebut <=  :debut', 'n.dateFin > :debut'),
                $qb->expr()->andX('n.dateDebut >= :debut', 'n.dateFin <= :fin'),
                $qb->expr()->andX('n.dateDebut <= :debut', 'n.dateFin <= :fin','n.dateFin > :debut'),
                $qb->expr()->andX('n.dateDebut >= :debut','n.dateFin >= :fin', 'n.dateDebut < :fin'
                    )
                ));
        
        $qb->setParameters($parameters);
        return $qb->getQuery()->getResult();
    }
    
}
